### ISSUE TITLE
Add ability pass in POCO classes into constructor of mocked class

### ISSUE THREAD

**Issue by jon49** [markjsc/AutoMockHelper#6]
**Is your feature request related to a problem? Please describe.**

When I am mocking a class I have to make my POCO classes an interface for the constructor. I would prefer to not have to make the code base more complicated just to use this library.

**Describe the solution you'd like**

I would like to be able to inject a POCO class into the constructor without needed to make it an interface.

E.g.,

```csharp
InstanceFor<MyClass>(new MyClass { MyProp = "I wasn't mocked. Isn't that wonderful! :-)" } );
```

**Describe alternatives you've considered**

I looked at the possible methods and was not able to see anything which would work.

**Additional context**

**Comment by markjsc** [comment]
Hi Jon,

Thanks so much for taking time to submit this request. I'll take a look at it in the coming days.

Best,
Mark

**Comment by markjsc** [comment]
@jon49 - Can you provide a bit more details about what you're trying to accomplish? I'm trying to understand your request. 

It sounds like you're asking whether you can pass concrete classes (POCOs) as constructor parameters into a class that you're mocking. Is that correct? For instance, your the class you're mocking would be something like this:
```cs
public OrderProcessor(INotificationService notificationService,
    IInventoryService inventoryService,
    IOrderRepository orderRepository,
    IOrderNumberGeneratorService orderNumberGeneratorService,
    ILogger logger,
    MyConcreteService instanceOfMyConcreteService,
    MyConcreteDataObject instanceOfMyConcreteDataObject)
{
}
```
I'm thinking you're asking about the last two parameters above (MyConcreteService, MyConcreteDataService). Is that right?

And so the mocking would look like:
```cs
[TestClass]
public class OrderProcessorTests : AutoMockContext<OrderProcessor>
{
    [TestMethod]
    public async Task SomeTestMethod()
    {
        //Arrange
        this.MockFor<MyConcreteService>().Setup(x => x.SomeServiceMethod());
        this.MocKFor<MyConcreteDataObject>().SetupGet<string>(x => x.SomeProperty).Returns("SomeStringValue");

        //etc...
    }
}


```

Please clarify.

Thanks in advance,
Mark

**Comment by jon49** [comment]
Yes, that is what I'm asking. I'll give that a try. Thank you for replying and your patience! I won't have time to look at this until Monday. Have a good weekend!

**Comment by markjsc** [comment]
Hi @jon49 - thanks for clarifying.

One thing to keep in mind is the design principles behind dependency injection, which are key to writing decoupled, testable classes. The "d" in [SOLID](https://en.wikipedia.org/wiki/SOLID) states

> One should "depend upon abstractions, [not] concretions."

This means that the class you're testing (OrderProcessor in my example above) should only have Interfaces as dependencies, NOT concrete classes. This allows you to have one (or more) concrete implementation at runtime while using a different implementation for testing (which Mocking helps to abstract).

I can also understand your concern when it comes to simple POCO data classes and not wanting to complicate your codebase with both an Interface and a Class just for data structures. I think in that case, using the concrete class should be OK. For what it's worth, I generally try to avoid passing these as constructor arguments - perhaps you could pass them in using a separate method like .Initialize()? (Just an idea...)

Hope this helps!
-mark

**Comment by jon49** [comment]
Right, and I agree with that but I also think it is important to keep things as simple as possible (the KISS principle :-)). And when you have a POCO settings class creating an `interface` or putting `virtual` on every single property seems like it is making it unnecessarily complex since settings don't change and are always given the same values.

Using dependency injection with these allows for the settings to not be global in scope but just scoped to the particular class (and just create settings classes for each specific use case). I figured since we can use dependency injection frameworks with POCO classes it would make sense that with mocks we should be able to inject those same POCO classes with the values we would like in them.

Using an `Initialize` method seems like it is also making it unnecessarily complex and adds some risk to the code base since you have to remember to call that method before doing other work with the class. I guess for now we will use an interface or virtual properties but that just seems like a hack.

Personally, I'm not a huge fan of mocking at all since we should separate side affects from pure code and just test the pure code with unit tests and then use monads for the combination of pure and impure code which gives it a uniform way of dealing with errors and such (which puts the testing on the compiler rather than the developer for impure code). But I think we are still 10 years off as an industry before we go that direction. I think dependency injection still plays an important role especially when you have different services and you only know which one to call at run time. But anyways, that is a tangent.

Thanks for your help!

**Comment by markjsc** [comment]
@jon49 - One more thought I had on this.

Another way to provide settings to your classes - one that would align well with the Dependency Injection principle - is to use a Settings Provider instead of passing the settings class directly into the constructor.

It could look something like this:
```cs
interface ISettingsProvider
{
    YourSettingsClass GetSettings();
}

class YourClassToBeTested
{
    private readonly YourSettingsClass _settings;

    public YourClassToBeTested(ISomeDependency someDependency, ISettingsProvider settingsProvider)
    {
        this._settings = settingsProvider.GetSettings();
    }
}


//Tests
[TestClass]
class YourTestClass : AutoMockContext<YourClassToBeTested>
{
    [TestMethod]
    void SomeTestMethod()
    {
        //Arrange
        var settings = new YourSettingsClass { YourProperty1 = "SomeValue", YourProperty2 = 2 };
        this.MockFor<ISettingsProvider>().Setup(x => x.GetSettings()).Returns(settings);

       //etc...
    }
}
```
I think this would play nicely with [DI frameworks](https://stackoverflow.com/a/21348/1449192) as well as manually-instantiated classes.

Hope this is helpful,
Mark
